### ISSUE TITLE
error loading plugin synoindex

### ISSUE THREAD

**Issue by Trauma** [neomilium/beets-synoindex#1]
Beets fail to load synoindex module with the following error:

`** error loading plugin synoindex:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 254, in load_plugins
    namespace = __import__(modname, None, None)
  File "/synoindex/beetsplug/synoindex.py", line 78, in <module>
    @SynoIndex.listen('pluginload')
AttributeError: type object 'SynoIndex' has no attribute 'listen'`

Any help would be much appreciated!

**Comment by Trauma** [comment]
The error might comes from here i guess : http://beets.readthedocs.io/en/latest/dev/plugins.html?highlight=listener#listen-for-events

**Comment by neomilium** [comment]
Hi,
I do not use nor maintain this plugin.
Feel free to fork it or offer a PR.

**Comment by neomilium** [comment]
Fixed by #3
